# coding: utf-8

"""
    PowerFlex NAS Management REST API

    NAS Storage Management REST API definition.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SmbServerUnjoin(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain_user_name': 'str',
        'domain_password': 'str',
        'is_skip_ad_unjoin': 'bool'
    }

    attribute_map = {
        'domain_user_name': 'domain_user_name',
        'domain_password': 'domain_password',
        'is_skip_ad_unjoin': 'is_skip_AD_unjoin'
    }

    def __init__(self, domain_user_name=None, domain_password=None, is_skip_ad_unjoin=False):  # noqa: E501
        """SmbServerUnjoin - a model defined in Swagger"""  # noqa: E501
        self._domain_user_name = None
        self._domain_password = None
        self._is_skip_ad_unjoin = None
        self.discriminator = None
        if domain_user_name is not None:
            self.domain_user_name = domain_user_name
        if domain_password is not None:
            self.domain_password = domain_password
        if is_skip_ad_unjoin is not None:
            self.is_skip_ad_unjoin = is_skip_ad_unjoin

    @property
    def domain_user_name(self):
        """Gets the domain_user_name of this SmbServerUnjoin.  # noqa: E501

        Name of a domain-user with sufficient privileges to unjoin from the Active Directory domain.  # noqa: E501

        :return: The domain_user_name of this SmbServerUnjoin.  # noqa: E501
        :rtype: str
        """
        return self._domain_user_name

    @domain_user_name.setter
    def domain_user_name(self, domain_user_name):
        """Sets the domain_user_name of this SmbServerUnjoin.

        Name of a domain-user with sufficient privileges to unjoin from the Active Directory domain.  # noqa: E501

        :param domain_user_name: The domain_user_name of this SmbServerUnjoin.  # noqa: E501
        :type: str
        """

        self._domain_user_name = domain_user_name

    @property
    def domain_password(self):
        """Gets the domain_password of this SmbServerUnjoin.  # noqa: E501

        Password of the domain-user specified to unjoin from the Active Directory domain.  # noqa: E501

        :return: The domain_password of this SmbServerUnjoin.  # noqa: E501
        :rtype: str
        """
        return self._domain_password

    @domain_password.setter
    def domain_password(self, domain_password):
        """Sets the domain_password of this SmbServerUnjoin.

        Password of the domain-user specified to unjoin from the Active Directory domain.  # noqa: E501

        :param domain_password: The domain_password of this SmbServerUnjoin.  # noqa: E501
        :type: str
        """

        self._domain_password = domain_password

    @property
    def is_skip_ad_unjoin(self):
        """Gets the is_skip_ad_unjoin of this SmbServerUnjoin.  # noqa: E501

        If set to yes: Will not remove the account from the Active Directory. This is to be used in case that no DC is available.  # noqa: E501

        :return: The is_skip_ad_unjoin of this SmbServerUnjoin.  # noqa: E501
        :rtype: bool
        """
        return self._is_skip_ad_unjoin

    @is_skip_ad_unjoin.setter
    def is_skip_ad_unjoin(self, is_skip_ad_unjoin):
        """Sets the is_skip_ad_unjoin of this SmbServerUnjoin.

        If set to yes: Will not remove the account from the Active Directory. This is to be used in case that no DC is available.  # noqa: E501

        :param is_skip_ad_unjoin: The is_skip_ad_unjoin of this SmbServerUnjoin.  # noqa: E501
        :type: bool
        """

        self._is_skip_ad_unjoin = is_skip_ad_unjoin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SmbServerUnjoin, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmbServerUnjoin):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
