# coding: utf-8

"""
    PowerFlex NAS Management REST API

    NAS Storage Management REST API definition.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SnapshotRuleInstance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'interval': 'NasSnapshotRulesIntervalEnum',
        'time_of_day': 'str',
        'days_of_week': 'list[NasSnapshotRulesDaysOfWeekEnum]',
        'retention': 'int',
        'type': 'NasSnapshotRulesTypeEnum',
        'interval_l10n': 'str',
        'days_of_week_l10n': 'list[str]',
        'type_l10n': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'interval': 'interval',
        'time_of_day': 'time_of_day',
        'days_of_week': 'days_of_week',
        'retention': 'retention',
        'type': 'type',
        'interval_l10n': 'interval_l10n',
        'days_of_week_l10n': 'days_of_week_l10n',
        'type_l10n': 'type_l10n'
    }

    def __init__(self, id=None, name=None, interval=None, time_of_day=None, days_of_week=None, retention=None, type=None, interval_l10n=None, days_of_week_l10n=None, type_l10n=None):  # noqa: E501
        """SnapshotRuleInstance - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._interval = None
        self._time_of_day = None
        self._days_of_week = None
        self._retention = None
        self._type = None
        self._interval_l10n = None
        self._days_of_week_l10n = None
        self._type_l10n = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if interval is not None:
            self.interval = interval
        if time_of_day is not None:
            self.time_of_day = time_of_day
        if days_of_week is not None:
            self.days_of_week = days_of_week
        if retention is not None:
            self.retention = retention
        if type is not None:
            self.type = type
        if interval_l10n is not None:
            self.interval_l10n = interval_l10n
        if days_of_week_l10n is not None:
            self.days_of_week_l10n = days_of_week_l10n
        if type_l10n is not None:
            self.type_l10n = type_l10n

    @property
    def id(self):
        """Gets the id of this SnapshotRuleInstance.  # noqa: E501

        Unique identifier of the snapshot rule.  # noqa: E501

        :return: The id of this SnapshotRuleInstance.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SnapshotRuleInstance.

        Unique identifier of the snapshot rule.  # noqa: E501

        :param id: The id of this SnapshotRuleInstance.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SnapshotRuleInstance.  # noqa: E501

        Snapshot rule name. Use only AlphaNumeric chars.  # noqa: E501

        :return: The name of this SnapshotRuleInstance.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SnapshotRuleInstance.

        Snapshot rule name. Use only AlphaNumeric chars.  # noqa: E501

        :param name: The name of this SnapshotRuleInstance.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def interval(self):
        """Gets the interval of this SnapshotRuleInstance.  # noqa: E501


        :return: The interval of this SnapshotRuleInstance.  # noqa: E501
        :rtype: NasSnapshotRulesIntervalEnum
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this SnapshotRuleInstance.


        :param interval: The interval of this SnapshotRuleInstance.  # noqa: E501
        :type: NasSnapshotRulesIntervalEnum
        """

        self._interval = interval

    @property
    def time_of_day(self):
        """Gets the time_of_day of this SnapshotRuleInstance.  # noqa: E501

        Time of the day to take a snapshot, with UTC format \"hh:mm\" in 24 hour time format. Either the interval parameter or the time_of_day parameter will be set, but no both. if time_of_day specified, days_of_week also need to be specified.  # noqa: E501

        :return: The time_of_day of this SnapshotRuleInstance.  # noqa: E501
        :rtype: str
        """
        return self._time_of_day

    @time_of_day.setter
    def time_of_day(self, time_of_day):
        """Sets the time_of_day of this SnapshotRuleInstance.

        Time of the day to take a snapshot, with UTC format \"hh:mm\" in 24 hour time format. Either the interval parameter or the time_of_day parameter will be set, but no both. if time_of_day specified, days_of_week also need to be specified.  # noqa: E501

        :param time_of_day: The time_of_day of this SnapshotRuleInstance.  # noqa: E501
        :type: str
        """

        self._time_of_day = time_of_day

    @property
    def days_of_week(self):
        """Gets the days_of_week of this SnapshotRuleInstance.  # noqa: E501

        Days of the week when the rule should be applied.  # noqa: E501

        :return: The days_of_week of this SnapshotRuleInstance.  # noqa: E501
        :rtype: list[NasSnapshotRulesDaysOfWeekEnum]
        """
        return self._days_of_week

    @days_of_week.setter
    def days_of_week(self, days_of_week):
        """Sets the days_of_week of this SnapshotRuleInstance.

        Days of the week when the rule should be applied.  # noqa: E501

        :param days_of_week: The days_of_week of this SnapshotRuleInstance.  # noqa: E501
        :type: list[NasSnapshotRulesDaysOfWeekEnum]
        """

        self._days_of_week = days_of_week

    @property
    def retention(self):
        """Gets the retention of this SnapshotRuleInstance.  # noqa: E501

        No. of hours since creation, snapshot must be retained in the system.  # noqa: E501

        :return: The retention of this SnapshotRuleInstance.  # noqa: E501
        :rtype: int
        """
        return self._retention

    @retention.setter
    def retention(self, retention):
        """Sets the retention of this SnapshotRuleInstance.

        No. of hours since creation, snapshot must be retained in the system.  # noqa: E501

        :param retention: The retention of this SnapshotRuleInstance.  # noqa: E501
        :type: int
        """

        self._retention = retention

    @property
    def type(self):
        """Gets the type of this SnapshotRuleInstance.  # noqa: E501


        :return: The type of this SnapshotRuleInstance.  # noqa: E501
        :rtype: NasSnapshotRulesTypeEnum
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SnapshotRuleInstance.


        :param type: The type of this SnapshotRuleInstance.  # noqa: E501
        :type: NasSnapshotRulesTypeEnum
        """

        self._type = type

    @property
    def interval_l10n(self):
        """Gets the interval_l10n of this SnapshotRuleInstance.  # noqa: E501

        Localized message string corresponding to interval  # noqa: E501

        :return: The interval_l10n of this SnapshotRuleInstance.  # noqa: E501
        :rtype: str
        """
        return self._interval_l10n

    @interval_l10n.setter
    def interval_l10n(self, interval_l10n):
        """Sets the interval_l10n of this SnapshotRuleInstance.

        Localized message string corresponding to interval  # noqa: E501

        :param interval_l10n: The interval_l10n of this SnapshotRuleInstance.  # noqa: E501
        :type: str
        """

        self._interval_l10n = interval_l10n

    @property
    def days_of_week_l10n(self):
        """Gets the days_of_week_l10n of this SnapshotRuleInstance.  # noqa: E501

        Localized message array corresponding to days_of_week  # noqa: E501

        :return: The days_of_week_l10n of this SnapshotRuleInstance.  # noqa: E501
        :rtype: list[str]
        """
        return self._days_of_week_l10n

    @days_of_week_l10n.setter
    def days_of_week_l10n(self, days_of_week_l10n):
        """Sets the days_of_week_l10n of this SnapshotRuleInstance.

        Localized message array corresponding to days_of_week  # noqa: E501

        :param days_of_week_l10n: The days_of_week_l10n of this SnapshotRuleInstance.  # noqa: E501
        :type: list[str]
        """

        self._days_of_week_l10n = days_of_week_l10n

    @property
    def type_l10n(self):
        """Gets the type_l10n of this SnapshotRuleInstance.  # noqa: E501

        Localized message string corresponding to type  # noqa: E501

        :return: The type_l10n of this SnapshotRuleInstance.  # noqa: E501
        :rtype: str
        """
        return self._type_l10n

    @type_l10n.setter
    def type_l10n(self, type_l10n):
        """Sets the type_l10n of this SnapshotRuleInstance.

        Localized message string corresponding to type  # noqa: E501

        :param type_l10n: The type_l10n of this SnapshotRuleInstance.  # noqa: E501
        :type: str
        """

        self._type_l10n = type_l10n

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SnapshotRuleInstance, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SnapshotRuleInstance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
