# coding: utf-8

"""
    PowerStore REST API

    Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )  # noqa: E501

    OpenAPI spec version: 3.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import prime.swagger_client
from prime.swagger_client.api.volume_api import VolumeApi  # noqa: E501
from prime.swagger_client.rest import ApiException


class TestVolumeApi(unittest.TestCase):
    """VolumeApi unit test stubs"""

    def setUp(self):
        self.api = prime.swagger_client.api.volume_api.VolumeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_volume_get(self):
        """Test case for volume_get

        Collection Query  # noqa: E501
        """
        pass

    def test_volume_id_attach_post(self):
        """Test case for volume_id_attach_post

        Attach  # noqa: E501
        """
        pass

    def test_volume_id_clone_post(self):
        """Test case for volume_id_clone_post

        Clone  # noqa: E501
        """
        pass

    def test_volume_id_configure_metro_post(self):
        """Test case for volume_id_configure_metro_post

        Configure Metro  # noqa: E501
        """
        pass

    def test_volume_id_delete(self):
        """Test case for volume_id_delete

        Delete  # noqa: E501
        """
        pass

    def test_volume_id_detach_post(self):
        """Test case for volume_id_detach_post

        Detach  # noqa: E501
        """
        pass

    def test_volume_id_end_metro_post(self):
        """Test case for volume_id_end_metro_post

        End Metro Configuration  # noqa: E501
        """
        pass

    def test_volume_id_get(self):
        """Test case for volume_id_get

        Instance Query  # noqa: E501
        """
        pass

    def test_volume_id_patch(self):
        """Test case for volume_id_patch

        Modify  # noqa: E501
        """
        pass

    def test_volume_id_refresh_post(self):
        """Test case for volume_id_refresh_post

        Refresh  # noqa: E501
        """
        pass

    def test_volume_id_restore_post(self):
        """Test case for volume_id_restore_post

        Restore  # noqa: E501
        """
        pass

    def test_volume_id_snapshot_post(self):
        """Test case for volume_id_snapshot_post

        Snapshot  # noqa: E501
        """
        pass

    def test_volume_post(self):
        """Test case for volume_post

        Create  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
