# coding: utf-8

"""
    PowerStore REST API

    Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )  # noqa: E501

    OpenAPI spec version: 3.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import prime.swagger_client
from prime.swagger_client.models.base_copy_metrics_by_volume import BaseCopyMetricsByVolume  # noqa: E501
from prime.swagger_client.rest import ApiException


class TestBaseCopyMetricsByVolume(unittest.TestCase):
    """BaseCopyMetricsByVolume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseCopyMetricsByVolume(self):
        """Test BaseCopyMetricsByVolume"""
        # FIXME: construct object with mandatory attributes with example values
        # model = prime.swagger_client.models.base_copy_metrics_by_volume.BaseCopyMetricsByVolume()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
