# coding: utf-8

"""
    PowerStore REST API

    Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )  # noqa: E501

    OpenAPI spec version: 3.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import prime.swagger_client
from prime.swagger_client.models.nfs_export_instance import NfsExportInstance  # noqa: E501
from prime.swagger_client.rest import ApiException


class TestNfsExportInstance(unittest.TestCase):
    """NfsExportInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNfsExportInstance(self):
        """Test NfsExportInstance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = prime.swagger_client.models.nfs_export_instance.NfsExportInstance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
