# coding: utf-8

"""
    PowerStore REST API

    Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )  # noqa: E501

    OpenAPI spec version: 3.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import prime.swagger_client
from prime.swagger_client.models.file_interface_source_parameters import FileInterfaceSourceParameters  # noqa: E501
from prime.swagger_client.rest import ApiException


class TestFileInterfaceSourceParameters(unittest.TestCase):
    """FileInterfaceSourceParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileInterfaceSourceParameters(self):
        """Test FileInterfaceSourceParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = prime.swagger_client.models.file_interface_source_parameters.FileInterfaceSourceParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
