# coding: utf-8

"""
    PowerFlex NAS Management REST API

    NAS Storage Management REST API definition.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.smb_server_create import SmbServerCreate  # noqa: E501
from swagger_client.rest import ApiException


class TestSmbServerCreate(unittest.TestCase):
    """SmbServerCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSmbServerCreate(self):
        """Test SmbServerCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.smb_server_create.SmbServerCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
