# coding: utf-8

"""
    PowerFlex NAS Management REST API

    NAS Storage Management REST API definition.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.id_keytab_body import IdKeytabBody  # noqa: E501
from swagger_client.rest import ApiException


class TestIdKeytabBody(unittest.TestCase):
    """IdKeytabBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdKeytabBody(self):
        """Test IdKeytabBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.id_keytab_body.IdKeytabBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
