# coding: utf-8

"""
    PowerStore REST API

    Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )  # noqa: E501

    OpenAPI spec version: 3.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from prime.swagger_client.configuration import Configuration


class PerformanceMetricsByFeFcNodeRollup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'node_id': 'str',
        'timestamp': 'datetime',
        'avg_read_latency': 'float',
        'avg_write_latency': 'float',
        'avg_latency': 'float',
        'avg_read_size': 'float',
        'avg_write_size': 'float',
        'avg_io_size': 'float',
        'avg_read_iops': 'float',
        'avg_write_iops': 'float',
        'avg_total_iops': 'float',
        'avg_read_bandwidth': 'float',
        'avg_write_bandwidth': 'float',
        'avg_total_bandwidth': 'float',
        'avg_unaligned_read_iops': 'float',
        'avg_unaligned_write_iops': 'float',
        'avg_unaligned_iops': 'float',
        'avg_unaligned_read_bandwidth': 'float',
        'avg_unaligned_write_bandwidth': 'float',
        'avg_unaligned_bandwidth': 'float',
        'avg_current_logins': 'int',
        'max_avg_read_latency': 'float',
        'max_avg_write_latency': 'float',
        'max_avg_latency': 'float',
        'max_avg_read_size': 'float',
        'max_avg_write_size': 'float',
        'max_avg_io_size': 'float',
        'max_read_iops': 'float',
        'max_write_iops': 'float',
        'max_total_iops': 'float',
        'max_read_bandwidth': 'float',
        'max_write_bandwidth': 'float',
        'max_total_bandwidth': 'float',
        'max_unaligned_read_iops': 'float',
        'max_unaligned_write_iops': 'float',
        'max_unaligned_iops': 'float',
        'max_unaligned_read_bandwidth': 'float',
        'max_unaligned_write_bandwidth': 'float',
        'max_unaligned_bandwidth': 'float',
        'max_current_logins': 'int',
        'avg_dumped_frames_ps': 'float',
        'avg_loss_of_signal_count_ps': 'float',
        'avg_invalid_crc_count_ps': 'float',
        'avg_loss_of_sync_count_ps': 'float',
        'avg_invalid_tx_word_count_ps': 'float',
        'avg_prim_seq_prot_err_count_ps': 'float',
        'avg_link_failure_count_ps': 'float',
        'max_dumped_frames_ps': 'float',
        'max_loss_of_signal_count_ps': 'float',
        'max_invalid_crc_count_ps': 'float',
        'max_loss_of_sync_count_ps': 'float',
        'max_invalid_tx_word_count_ps': 'float',
        'max_prim_seq_prot_err_count_ps': 'float',
        'max_link_failure_count_ps': 'float',
        'repeat_count': 'int'
    }

    attribute_map = {
        'node_id': 'node_id',
        'timestamp': 'timestamp',
        'avg_read_latency': 'avg_read_latency',
        'avg_write_latency': 'avg_write_latency',
        'avg_latency': 'avg_latency',
        'avg_read_size': 'avg_read_size',
        'avg_write_size': 'avg_write_size',
        'avg_io_size': 'avg_io_size',
        'avg_read_iops': 'avg_read_iops',
        'avg_write_iops': 'avg_write_iops',
        'avg_total_iops': 'avg_total_iops',
        'avg_read_bandwidth': 'avg_read_bandwidth',
        'avg_write_bandwidth': 'avg_write_bandwidth',
        'avg_total_bandwidth': 'avg_total_bandwidth',
        'avg_unaligned_read_iops': 'avg_unaligned_read_iops',
        'avg_unaligned_write_iops': 'avg_unaligned_write_iops',
        'avg_unaligned_iops': 'avg_unaligned_iops',
        'avg_unaligned_read_bandwidth': 'avg_unaligned_read_bandwidth',
        'avg_unaligned_write_bandwidth': 'avg_unaligned_write_bandwidth',
        'avg_unaligned_bandwidth': 'avg_unaligned_bandwidth',
        'avg_current_logins': 'avg_current_logins',
        'max_avg_read_latency': 'max_avg_read_latency',
        'max_avg_write_latency': 'max_avg_write_latency',
        'max_avg_latency': 'max_avg_latency',
        'max_avg_read_size': 'max_avg_read_size',
        'max_avg_write_size': 'max_avg_write_size',
        'max_avg_io_size': 'max_avg_io_size',
        'max_read_iops': 'max_read_iops',
        'max_write_iops': 'max_write_iops',
        'max_total_iops': 'max_total_iops',
        'max_read_bandwidth': 'max_read_bandwidth',
        'max_write_bandwidth': 'max_write_bandwidth',
        'max_total_bandwidth': 'max_total_bandwidth',
        'max_unaligned_read_iops': 'max_unaligned_read_iops',
        'max_unaligned_write_iops': 'max_unaligned_write_iops',
        'max_unaligned_iops': 'max_unaligned_iops',
        'max_unaligned_read_bandwidth': 'max_unaligned_read_bandwidth',
        'max_unaligned_write_bandwidth': 'max_unaligned_write_bandwidth',
        'max_unaligned_bandwidth': 'max_unaligned_bandwidth',
        'max_current_logins': 'max_current_logins',
        'avg_dumped_frames_ps': 'avg_dumped_frames_ps',
        'avg_loss_of_signal_count_ps': 'avg_loss_of_signal_count_ps',
        'avg_invalid_crc_count_ps': 'avg_invalid_crc_count_ps',
        'avg_loss_of_sync_count_ps': 'avg_loss_of_sync_count_ps',
        'avg_invalid_tx_word_count_ps': 'avg_invalid_tx_word_count_ps',
        'avg_prim_seq_prot_err_count_ps': 'avg_prim_seq_prot_err_count_ps',
        'avg_link_failure_count_ps': 'avg_link_failure_count_ps',
        'max_dumped_frames_ps': 'max_dumped_frames_ps',
        'max_loss_of_signal_count_ps': 'max_loss_of_signal_count_ps',
        'max_invalid_crc_count_ps': 'max_invalid_crc_count_ps',
        'max_loss_of_sync_count_ps': 'max_loss_of_sync_count_ps',
        'max_invalid_tx_word_count_ps': 'max_invalid_tx_word_count_ps',
        'max_prim_seq_prot_err_count_ps': 'max_prim_seq_prot_err_count_ps',
        'max_link_failure_count_ps': 'max_link_failure_count_ps',
        'repeat_count': 'repeat_count'
    }

    def __init__(self, node_id=None, timestamp=None, avg_read_latency=None, avg_write_latency=None, avg_latency=None, avg_read_size=None, avg_write_size=None, avg_io_size=None, avg_read_iops=None, avg_write_iops=None, avg_total_iops=None, avg_read_bandwidth=None, avg_write_bandwidth=None, avg_total_bandwidth=None, avg_unaligned_read_iops=None, avg_unaligned_write_iops=None, avg_unaligned_iops=None, avg_unaligned_read_bandwidth=None, avg_unaligned_write_bandwidth=None, avg_unaligned_bandwidth=None, avg_current_logins=None, max_avg_read_latency=None, max_avg_write_latency=None, max_avg_latency=None, max_avg_read_size=None, max_avg_write_size=None, max_avg_io_size=None, max_read_iops=None, max_write_iops=None, max_total_iops=None, max_read_bandwidth=None, max_write_bandwidth=None, max_total_bandwidth=None, max_unaligned_read_iops=None, max_unaligned_write_iops=None, max_unaligned_iops=None, max_unaligned_read_bandwidth=None, max_unaligned_write_bandwidth=None, max_unaligned_bandwidth=None, max_current_logins=None, avg_dumped_frames_ps=None, avg_loss_of_signal_count_ps=None, avg_invalid_crc_count_ps=None, avg_loss_of_sync_count_ps=None, avg_invalid_tx_word_count_ps=None, avg_prim_seq_prot_err_count_ps=None, avg_link_failure_count_ps=None, max_dumped_frames_ps=None, max_loss_of_signal_count_ps=None, max_invalid_crc_count_ps=None, max_loss_of_sync_count_ps=None, max_invalid_tx_word_count_ps=None, max_prim_seq_prot_err_count_ps=None, max_link_failure_count_ps=None, repeat_count=None, _configuration=None):  # noqa: E501
        """PerformanceMetricsByFeFcNodeRollup - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._node_id = None
        self._timestamp = None
        self._avg_read_latency = None
        self._avg_write_latency = None
        self._avg_latency = None
        self._avg_read_size = None
        self._avg_write_size = None
        self._avg_io_size = None
        self._avg_read_iops = None
        self._avg_write_iops = None
        self._avg_total_iops = None
        self._avg_read_bandwidth = None
        self._avg_write_bandwidth = None
        self._avg_total_bandwidth = None
        self._avg_unaligned_read_iops = None
        self._avg_unaligned_write_iops = None
        self._avg_unaligned_iops = None
        self._avg_unaligned_read_bandwidth = None
        self._avg_unaligned_write_bandwidth = None
        self._avg_unaligned_bandwidth = None
        self._avg_current_logins = None
        self._max_avg_read_latency = None
        self._max_avg_write_latency = None
        self._max_avg_latency = None
        self._max_avg_read_size = None
        self._max_avg_write_size = None
        self._max_avg_io_size = None
        self._max_read_iops = None
        self._max_write_iops = None
        self._max_total_iops = None
        self._max_read_bandwidth = None
        self._max_write_bandwidth = None
        self._max_total_bandwidth = None
        self._max_unaligned_read_iops = None
        self._max_unaligned_write_iops = None
        self._max_unaligned_iops = None
        self._max_unaligned_read_bandwidth = None
        self._max_unaligned_write_bandwidth = None
        self._max_unaligned_bandwidth = None
        self._max_current_logins = None
        self._avg_dumped_frames_ps = None
        self._avg_loss_of_signal_count_ps = None
        self._avg_invalid_crc_count_ps = None
        self._avg_loss_of_sync_count_ps = None
        self._avg_invalid_tx_word_count_ps = None
        self._avg_prim_seq_prot_err_count_ps = None
        self._avg_link_failure_count_ps = None
        self._max_dumped_frames_ps = None
        self._max_loss_of_signal_count_ps = None
        self._max_invalid_crc_count_ps = None
        self._max_loss_of_sync_count_ps = None
        self._max_invalid_tx_word_count_ps = None
        self._max_prim_seq_prot_err_count_ps = None
        self._max_link_failure_count_ps = None
        self._repeat_count = None
        self.discriminator = None

        if node_id is not None:
            self.node_id = node_id
        if timestamp is not None:
            self.timestamp = timestamp
        if avg_read_latency is not None:
            self.avg_read_latency = avg_read_latency
        if avg_write_latency is not None:
            self.avg_write_latency = avg_write_latency
        if avg_latency is not None:
            self.avg_latency = avg_latency
        if avg_read_size is not None:
            self.avg_read_size = avg_read_size
        if avg_write_size is not None:
            self.avg_write_size = avg_write_size
        if avg_io_size is not None:
            self.avg_io_size = avg_io_size
        if avg_read_iops is not None:
            self.avg_read_iops = avg_read_iops
        if avg_write_iops is not None:
            self.avg_write_iops = avg_write_iops
        if avg_total_iops is not None:
            self.avg_total_iops = avg_total_iops
        if avg_read_bandwidth is not None:
            self.avg_read_bandwidth = avg_read_bandwidth
        if avg_write_bandwidth is not None:
            self.avg_write_bandwidth = avg_write_bandwidth
        if avg_total_bandwidth is not None:
            self.avg_total_bandwidth = avg_total_bandwidth
        if avg_unaligned_read_iops is not None:
            self.avg_unaligned_read_iops = avg_unaligned_read_iops
        if avg_unaligned_write_iops is not None:
            self.avg_unaligned_write_iops = avg_unaligned_write_iops
        if avg_unaligned_iops is not None:
            self.avg_unaligned_iops = avg_unaligned_iops
        if avg_unaligned_read_bandwidth is not None:
            self.avg_unaligned_read_bandwidth = avg_unaligned_read_bandwidth
        if avg_unaligned_write_bandwidth is not None:
            self.avg_unaligned_write_bandwidth = avg_unaligned_write_bandwidth
        if avg_unaligned_bandwidth is not None:
            self.avg_unaligned_bandwidth = avg_unaligned_bandwidth
        if avg_current_logins is not None:
            self.avg_current_logins = avg_current_logins
        if max_avg_read_latency is not None:
            self.max_avg_read_latency = max_avg_read_latency
        if max_avg_write_latency is not None:
            self.max_avg_write_latency = max_avg_write_latency
        if max_avg_latency is not None:
            self.max_avg_latency = max_avg_latency
        if max_avg_read_size is not None:
            self.max_avg_read_size = max_avg_read_size
        if max_avg_write_size is not None:
            self.max_avg_write_size = max_avg_write_size
        if max_avg_io_size is not None:
            self.max_avg_io_size = max_avg_io_size
        if max_read_iops is not None:
            self.max_read_iops = max_read_iops
        if max_write_iops is not None:
            self.max_write_iops = max_write_iops
        if max_total_iops is not None:
            self.max_total_iops = max_total_iops
        if max_read_bandwidth is not None:
            self.max_read_bandwidth = max_read_bandwidth
        if max_write_bandwidth is not None:
            self.max_write_bandwidth = max_write_bandwidth
        if max_total_bandwidth is not None:
            self.max_total_bandwidth = max_total_bandwidth
        if max_unaligned_read_iops is not None:
            self.max_unaligned_read_iops = max_unaligned_read_iops
        if max_unaligned_write_iops is not None:
            self.max_unaligned_write_iops = max_unaligned_write_iops
        if max_unaligned_iops is not None:
            self.max_unaligned_iops = max_unaligned_iops
        if max_unaligned_read_bandwidth is not None:
            self.max_unaligned_read_bandwidth = max_unaligned_read_bandwidth
        if max_unaligned_write_bandwidth is not None:
            self.max_unaligned_write_bandwidth = max_unaligned_write_bandwidth
        if max_unaligned_bandwidth is not None:
            self.max_unaligned_bandwidth = max_unaligned_bandwidth
        if max_current_logins is not None:
            self.max_current_logins = max_current_logins
        if avg_dumped_frames_ps is not None:
            self.avg_dumped_frames_ps = avg_dumped_frames_ps
        if avg_loss_of_signal_count_ps is not None:
            self.avg_loss_of_signal_count_ps = avg_loss_of_signal_count_ps
        if avg_invalid_crc_count_ps is not None:
            self.avg_invalid_crc_count_ps = avg_invalid_crc_count_ps
        if avg_loss_of_sync_count_ps is not None:
            self.avg_loss_of_sync_count_ps = avg_loss_of_sync_count_ps
        if avg_invalid_tx_word_count_ps is not None:
            self.avg_invalid_tx_word_count_ps = avg_invalid_tx_word_count_ps
        if avg_prim_seq_prot_err_count_ps is not None:
            self.avg_prim_seq_prot_err_count_ps = avg_prim_seq_prot_err_count_ps
        if avg_link_failure_count_ps is not None:
            self.avg_link_failure_count_ps = avg_link_failure_count_ps
        if max_dumped_frames_ps is not None:
            self.max_dumped_frames_ps = max_dumped_frames_ps
        if max_loss_of_signal_count_ps is not None:
            self.max_loss_of_signal_count_ps = max_loss_of_signal_count_ps
        if max_invalid_crc_count_ps is not None:
            self.max_invalid_crc_count_ps = max_invalid_crc_count_ps
        if max_loss_of_sync_count_ps is not None:
            self.max_loss_of_sync_count_ps = max_loss_of_sync_count_ps
        if max_invalid_tx_word_count_ps is not None:
            self.max_invalid_tx_word_count_ps = max_invalid_tx_word_count_ps
        if max_prim_seq_prot_err_count_ps is not None:
            self.max_prim_seq_prot_err_count_ps = max_prim_seq_prot_err_count_ps
        if max_link_failure_count_ps is not None:
            self.max_link_failure_count_ps = max_link_failure_count_ps
        if repeat_count is not None:
            self.repeat_count = repeat_count

    @property
    def node_id(self):
        """Gets the node_id of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Reference to the associated node on which these metrics were recorded.  # noqa: E501

        :return: The node_id of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this PerformanceMetricsByFeFcNodeRollup.

        Reference to the associated node on which these metrics were recorded.  # noqa: E501

        :param node_id: The node_id of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: str
        """

        self._node_id = node_id

    @property
    def timestamp(self):
        """Gets the timestamp of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        End of sample period.  # noqa: E501

        :return: The timestamp of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this PerformanceMetricsByFeFcNodeRollup.

        End of sample period.  # noqa: E501

        :param timestamp: The timestamp of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    @property
    def avg_read_latency(self):
        """Gets the avg_read_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Weighted average read latency in microseconds.  # noqa: E501

        :return: The avg_read_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_read_latency

    @avg_read_latency.setter
    def avg_read_latency(self, avg_read_latency):
        """Sets the avg_read_latency of this PerformanceMetricsByFeFcNodeRollup.

        Weighted average read latency in microseconds.  # noqa: E501

        :param avg_read_latency: The avg_read_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_read_latency = avg_read_latency

    @property
    def avg_write_latency(self):
        """Gets the avg_write_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Weighted average  write latency in microseconds.  # noqa: E501

        :return: The avg_write_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_write_latency

    @avg_write_latency.setter
    def avg_write_latency(self, avg_write_latency):
        """Sets the avg_write_latency of this PerformanceMetricsByFeFcNodeRollup.

        Weighted average  write latency in microseconds.  # noqa: E501

        :param avg_write_latency: The avg_write_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_write_latency = avg_write_latency

    @property
    def avg_latency(self):
        """Gets the avg_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Weighted average  latency in microseconds.  # noqa: E501

        :return: The avg_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_latency

    @avg_latency.setter
    def avg_latency(self, avg_latency):
        """Sets the avg_latency of this PerformanceMetricsByFeFcNodeRollup.

        Weighted average  latency in microseconds.  # noqa: E501

        :param avg_latency: The avg_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_latency = avg_latency

    @property
    def avg_read_size(self):
        """Gets the avg_read_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Weighted average read size in bytes.  # noqa: E501

        :return: The avg_read_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_read_size

    @avg_read_size.setter
    def avg_read_size(self, avg_read_size):
        """Sets the avg_read_size of this PerformanceMetricsByFeFcNodeRollup.

        Weighted average read size in bytes.  # noqa: E501

        :param avg_read_size: The avg_read_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_read_size = avg_read_size

    @property
    def avg_write_size(self):
        """Gets the avg_write_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Weighted average write size in bytes.  # noqa: E501

        :return: The avg_write_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_write_size

    @avg_write_size.setter
    def avg_write_size(self, avg_write_size):
        """Sets the avg_write_size of this PerformanceMetricsByFeFcNodeRollup.

        Weighted average write size in bytes.  # noqa: E501

        :param avg_write_size: The avg_write_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_write_size = avg_write_size

    @property
    def avg_io_size(self):
        """Gets the avg_io_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average size of read and write operations in bytes.  # noqa: E501

        :return: The avg_io_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_io_size

    @avg_io_size.setter
    def avg_io_size(self, avg_io_size):
        """Sets the avg_io_size of this PerformanceMetricsByFeFcNodeRollup.

        Average size of read and write operations in bytes.  # noqa: E501

        :param avg_io_size: The avg_io_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_io_size = avg_io_size

    @property
    def avg_read_iops(self):
        """Gets the avg_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average reads per second.  # noqa: E501

        :return: The avg_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_read_iops

    @avg_read_iops.setter
    def avg_read_iops(self, avg_read_iops):
        """Sets the avg_read_iops of this PerformanceMetricsByFeFcNodeRollup.

        Average reads per second.  # noqa: E501

        :param avg_read_iops: The avg_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_read_iops = avg_read_iops

    @property
    def avg_write_iops(self):
        """Gets the avg_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average writes per second.  # noqa: E501

        :return: The avg_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_write_iops

    @avg_write_iops.setter
    def avg_write_iops(self, avg_write_iops):
        """Sets the avg_write_iops of this PerformanceMetricsByFeFcNodeRollup.

        Average writes per second.  # noqa: E501

        :param avg_write_iops: The avg_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_write_iops = avg_write_iops

    @property
    def avg_total_iops(self):
        """Gets the avg_total_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average total input and output operations per second.  # noqa: E501

        :return: The avg_total_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_total_iops

    @avg_total_iops.setter
    def avg_total_iops(self, avg_total_iops):
        """Sets the avg_total_iops of this PerformanceMetricsByFeFcNodeRollup.

        Average total input and output operations per second.  # noqa: E501

        :param avg_total_iops: The avg_total_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_total_iops = avg_total_iops

    @property
    def avg_read_bandwidth(self):
        """Gets the avg_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Weighted average read bandwidth in bytes per second.  # noqa: E501

        :return: The avg_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_read_bandwidth

    @avg_read_bandwidth.setter
    def avg_read_bandwidth(self, avg_read_bandwidth):
        """Sets the avg_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Weighted average read bandwidth in bytes per second.  # noqa: E501

        :param avg_read_bandwidth: The avg_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_read_bandwidth = avg_read_bandwidth

    @property
    def avg_write_bandwidth(self):
        """Gets the avg_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Weighted average write bandwidth in bytes per second.  # noqa: E501

        :return: The avg_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_write_bandwidth

    @avg_write_bandwidth.setter
    def avg_write_bandwidth(self, avg_write_bandwidth):
        """Sets the avg_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Weighted average write bandwidth in bytes per second.  # noqa: E501

        :param avg_write_bandwidth: The avg_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_write_bandwidth = avg_write_bandwidth

    @property
    def avg_total_bandwidth(self):
        """Gets the avg_total_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Weighted average total bandwidth in bytes per second.  # noqa: E501

        :return: The avg_total_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_total_bandwidth

    @avg_total_bandwidth.setter
    def avg_total_bandwidth(self, avg_total_bandwidth):
        """Sets the avg_total_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Weighted average total bandwidth in bytes per second.  # noqa: E501

        :param avg_total_bandwidth: The avg_total_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_total_bandwidth = avg_total_bandwidth

    @property
    def avg_unaligned_read_iops(self):
        """Gets the avg_unaligned_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average unaligned read input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The avg_unaligned_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_unaligned_read_iops

    @avg_unaligned_read_iops.setter
    def avg_unaligned_read_iops(self, avg_unaligned_read_iops):
        """Sets the avg_unaligned_read_iops of this PerformanceMetricsByFeFcNodeRollup.

        Average unaligned read input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param avg_unaligned_read_iops: The avg_unaligned_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_unaligned_read_iops = avg_unaligned_read_iops

    @property
    def avg_unaligned_write_iops(self):
        """Gets the avg_unaligned_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average unaligned write input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The avg_unaligned_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_unaligned_write_iops

    @avg_unaligned_write_iops.setter
    def avg_unaligned_write_iops(self, avg_unaligned_write_iops):
        """Sets the avg_unaligned_write_iops of this PerformanceMetricsByFeFcNodeRollup.

        Average unaligned write input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param avg_unaligned_write_iops: The avg_unaligned_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_unaligned_write_iops = avg_unaligned_write_iops

    @property
    def avg_unaligned_iops(self):
        """Gets the avg_unaligned_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average unaligned total input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The avg_unaligned_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_unaligned_iops

    @avg_unaligned_iops.setter
    def avg_unaligned_iops(self, avg_unaligned_iops):
        """Sets the avg_unaligned_iops of this PerformanceMetricsByFeFcNodeRollup.

        Average unaligned total input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param avg_unaligned_iops: The avg_unaligned_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_unaligned_iops = avg_unaligned_iops

    @property
    def avg_unaligned_read_bandwidth(self):
        """Gets the avg_unaligned_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average unaligned read rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The avg_unaligned_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_unaligned_read_bandwidth

    @avg_unaligned_read_bandwidth.setter
    def avg_unaligned_read_bandwidth(self, avg_unaligned_read_bandwidth):
        """Sets the avg_unaligned_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Average unaligned read rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param avg_unaligned_read_bandwidth: The avg_unaligned_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_unaligned_read_bandwidth = avg_unaligned_read_bandwidth

    @property
    def avg_unaligned_write_bandwidth(self):
        """Gets the avg_unaligned_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average unaligned write rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The avg_unaligned_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_unaligned_write_bandwidth

    @avg_unaligned_write_bandwidth.setter
    def avg_unaligned_write_bandwidth(self, avg_unaligned_write_bandwidth):
        """Sets the avg_unaligned_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Average unaligned write rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param avg_unaligned_write_bandwidth: The avg_unaligned_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_unaligned_write_bandwidth = avg_unaligned_write_bandwidth

    @property
    def avg_unaligned_bandwidth(self):
        """Gets the avg_unaligned_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average unaligned read/write rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The avg_unaligned_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_unaligned_bandwidth

    @avg_unaligned_bandwidth.setter
    def avg_unaligned_bandwidth(self, avg_unaligned_bandwidth):
        """Sets the avg_unaligned_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Average unaligned read/write rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param avg_unaligned_bandwidth: The avg_unaligned_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_unaligned_bandwidth = avg_unaligned_bandwidth

    @property
    def avg_current_logins(self):
        """Gets the avg_current_logins of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average number of logins to the target from initiators.  # noqa: E501

        :return: The avg_current_logins of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: int
        """
        return self._avg_current_logins

    @avg_current_logins.setter
    def avg_current_logins(self, avg_current_logins):
        """Sets the avg_current_logins of this PerformanceMetricsByFeFcNodeRollup.

        Average number of logins to the target from initiators.  # noqa: E501

        :param avg_current_logins: The avg_current_logins of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                avg_current_logins is not None and avg_current_logins > -9223372036854775616):  # noqa: E501
            raise ValueError("Invalid value for `avg_current_logins`, must be a value less than or equal to `-9223372036854775616`")  # noqa: E501
        if (self._configuration.client_side_validation and
                avg_current_logins is not None and avg_current_logins < 0):  # noqa: E501
            raise ValueError("Invalid value for `avg_current_logins`, must be a value greater than or equal to `0`")  # noqa: E501

        self._avg_current_logins = avg_current_logins

    @property
    def max_avg_read_latency(self):
        """Gets the max_avg_read_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum read latency in microseconds.  # noqa: E501

        :return: The max_avg_read_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_avg_read_latency

    @max_avg_read_latency.setter
    def max_avg_read_latency(self, max_avg_read_latency):
        """Sets the max_avg_read_latency of this PerformanceMetricsByFeFcNodeRollup.

        Maximum read latency in microseconds.  # noqa: E501

        :param max_avg_read_latency: The max_avg_read_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_avg_read_latency = max_avg_read_latency

    @property
    def max_avg_write_latency(self):
        """Gets the max_avg_write_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum of average write latency in microseconds.  # noqa: E501

        :return: The max_avg_write_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_avg_write_latency

    @max_avg_write_latency.setter
    def max_avg_write_latency(self, max_avg_write_latency):
        """Sets the max_avg_write_latency of this PerformanceMetricsByFeFcNodeRollup.

        Maximum of average write latency in microseconds.  # noqa: E501

        :param max_avg_write_latency: The max_avg_write_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_avg_write_latency = max_avg_write_latency

    @property
    def max_avg_latency(self):
        """Gets the max_avg_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum of average latency in microseconds.  # noqa: E501

        :return: The max_avg_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_avg_latency

    @max_avg_latency.setter
    def max_avg_latency(self, max_avg_latency):
        """Sets the max_avg_latency of this PerformanceMetricsByFeFcNodeRollup.

        Maximum of average latency in microseconds.  # noqa: E501

        :param max_avg_latency: The max_avg_latency of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_avg_latency = max_avg_latency

    @property
    def max_avg_read_size(self):
        """Gets the max_avg_read_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum of average read size in bytes.  # noqa: E501

        :return: The max_avg_read_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_avg_read_size

    @max_avg_read_size.setter
    def max_avg_read_size(self, max_avg_read_size):
        """Sets the max_avg_read_size of this PerformanceMetricsByFeFcNodeRollup.

        Maximum of average read size in bytes.  # noqa: E501

        :param max_avg_read_size: The max_avg_read_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_avg_read_size = max_avg_read_size

    @property
    def max_avg_write_size(self):
        """Gets the max_avg_write_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum of average write size in bytes.  # noqa: E501

        :return: The max_avg_write_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_avg_write_size

    @max_avg_write_size.setter
    def max_avg_write_size(self, max_avg_write_size):
        """Sets the max_avg_write_size of this PerformanceMetricsByFeFcNodeRollup.

        Maximum of average write size in bytes.  # noqa: E501

        :param max_avg_write_size: The max_avg_write_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_avg_write_size = max_avg_write_size

    @property
    def max_avg_io_size(self):
        """Gets the max_avg_io_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum average size of input and output operations in bytes.  # noqa: E501

        :return: The max_avg_io_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_avg_io_size

    @max_avg_io_size.setter
    def max_avg_io_size(self, max_avg_io_size):
        """Sets the max_avg_io_size of this PerformanceMetricsByFeFcNodeRollup.

        Maximum average size of input and output operations in bytes.  # noqa: E501

        :param max_avg_io_size: The max_avg_io_size of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_avg_io_size = max_avg_io_size

    @property
    def max_read_iops(self):
        """Gets the max_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum reads per second.  # noqa: E501

        :return: The max_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_read_iops

    @max_read_iops.setter
    def max_read_iops(self, max_read_iops):
        """Sets the max_read_iops of this PerformanceMetricsByFeFcNodeRollup.

        Maximum reads per second.  # noqa: E501

        :param max_read_iops: The max_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_read_iops = max_read_iops

    @property
    def max_write_iops(self):
        """Gets the max_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum writes per second.  # noqa: E501

        :return: The max_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_write_iops

    @max_write_iops.setter
    def max_write_iops(self, max_write_iops):
        """Sets the max_write_iops of this PerformanceMetricsByFeFcNodeRollup.

        Maximum writes per second.  # noqa: E501

        :param max_write_iops: The max_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_write_iops = max_write_iops

    @property
    def max_total_iops(self):
        """Gets the max_total_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum totals per second.  # noqa: E501

        :return: The max_total_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_total_iops

    @max_total_iops.setter
    def max_total_iops(self, max_total_iops):
        """Sets the max_total_iops of this PerformanceMetricsByFeFcNodeRollup.

        Maximum totals per second.  # noqa: E501

        :param max_total_iops: The max_total_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_total_iops = max_total_iops

    @property
    def max_read_bandwidth(self):
        """Gets the max_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum read bandwidth in bytes per second.  # noqa: E501

        :return: The max_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_read_bandwidth

    @max_read_bandwidth.setter
    def max_read_bandwidth(self, max_read_bandwidth):
        """Sets the max_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Maximum read bandwidth in bytes per second.  # noqa: E501

        :param max_read_bandwidth: The max_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_read_bandwidth = max_read_bandwidth

    @property
    def max_write_bandwidth(self):
        """Gets the max_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum write bandwidth in bytes per second.  # noqa: E501

        :return: The max_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_write_bandwidth

    @max_write_bandwidth.setter
    def max_write_bandwidth(self, max_write_bandwidth):
        """Sets the max_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Maximum write bandwidth in bytes per second.  # noqa: E501

        :param max_write_bandwidth: The max_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_write_bandwidth = max_write_bandwidth

    @property
    def max_total_bandwidth(self):
        """Gets the max_total_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum total bandwidth in bytes per second.  # noqa: E501

        :return: The max_total_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_total_bandwidth

    @max_total_bandwidth.setter
    def max_total_bandwidth(self, max_total_bandwidth):
        """Sets the max_total_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Maximum total bandwidth in bytes per second.  # noqa: E501

        :param max_total_bandwidth: The max_total_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_total_bandwidth = max_total_bandwidth

    @property
    def max_unaligned_read_iops(self):
        """Gets the max_unaligned_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum unaligned read input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The max_unaligned_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_unaligned_read_iops

    @max_unaligned_read_iops.setter
    def max_unaligned_read_iops(self, max_unaligned_read_iops):
        """Sets the max_unaligned_read_iops of this PerformanceMetricsByFeFcNodeRollup.

        Maximum unaligned read input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param max_unaligned_read_iops: The max_unaligned_read_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_unaligned_read_iops = max_unaligned_read_iops

    @property
    def max_unaligned_write_iops(self):
        """Gets the max_unaligned_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum unaligned write input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The max_unaligned_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_unaligned_write_iops

    @max_unaligned_write_iops.setter
    def max_unaligned_write_iops(self, max_unaligned_write_iops):
        """Sets the max_unaligned_write_iops of this PerformanceMetricsByFeFcNodeRollup.

        Maximum unaligned write input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param max_unaligned_write_iops: The max_unaligned_write_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_unaligned_write_iops = max_unaligned_write_iops

    @property
    def max_unaligned_iops(self):
        """Gets the max_unaligned_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum unaligned total input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The max_unaligned_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_unaligned_iops

    @max_unaligned_iops.setter
    def max_unaligned_iops(self, max_unaligned_iops):
        """Sets the max_unaligned_iops of this PerformanceMetricsByFeFcNodeRollup.

        Maximum unaligned total input/output per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param max_unaligned_iops: The max_unaligned_iops of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_unaligned_iops = max_unaligned_iops

    @property
    def max_unaligned_read_bandwidth(self):
        """Gets the max_unaligned_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum unaligned read rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The max_unaligned_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_unaligned_read_bandwidth

    @max_unaligned_read_bandwidth.setter
    def max_unaligned_read_bandwidth(self, max_unaligned_read_bandwidth):
        """Sets the max_unaligned_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Maximum unaligned read rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param max_unaligned_read_bandwidth: The max_unaligned_read_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_unaligned_read_bandwidth = max_unaligned_read_bandwidth

    @property
    def max_unaligned_write_bandwidth(self):
        """Gets the max_unaligned_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum unaligned write rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The max_unaligned_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_unaligned_write_bandwidth

    @max_unaligned_write_bandwidth.setter
    def max_unaligned_write_bandwidth(self, max_unaligned_write_bandwidth):
        """Sets the max_unaligned_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Maximum unaligned write rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param max_unaligned_write_bandwidth: The max_unaligned_write_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_unaligned_write_bandwidth = max_unaligned_write_bandwidth

    @property
    def max_unaligned_bandwidth(self):
        """Gets the max_unaligned_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum unaligned read/write rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :return: The max_unaligned_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_unaligned_bandwidth

    @max_unaligned_bandwidth.setter
    def max_unaligned_bandwidth(self, max_unaligned_bandwidth):
        """Sets the max_unaligned_bandwidth of this PerformanceMetricsByFeFcNodeRollup.

        Maximum unaligned read/write rate in bytes per second. Was deprecated in version 2.1.0.0.  # noqa: E501

        :param max_unaligned_bandwidth: The max_unaligned_bandwidth of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_unaligned_bandwidth = max_unaligned_bandwidth

    @property
    def max_current_logins(self):
        """Gets the max_current_logins of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Maximum number of logins to the target from initiators.  # noqa: E501

        :return: The max_current_logins of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: int
        """
        return self._max_current_logins

    @max_current_logins.setter
    def max_current_logins(self, max_current_logins):
        """Sets the max_current_logins of this PerformanceMetricsByFeFcNodeRollup.

        Maximum number of logins to the target from initiators.  # noqa: E501

        :param max_current_logins: The max_current_logins of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                max_current_logins is not None and max_current_logins > -9223372036854775616):  # noqa: E501
            raise ValueError("Invalid value for `max_current_logins`, must be a value less than or equal to `-9223372036854775616`")  # noqa: E501
        if (self._configuration.client_side_validation and
                max_current_logins is not None and max_current_logins < 0):  # noqa: E501
            raise ValueError("Invalid value for `max_current_logins`, must be a value greater than or equal to `0`")  # noqa: E501

        self._max_current_logins = max_current_logins

    @property
    def avg_dumped_frames_ps(self):
        """Gets the avg_dumped_frames_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average dumped frames per second.  # noqa: E501

        :return: The avg_dumped_frames_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_dumped_frames_ps

    @avg_dumped_frames_ps.setter
    def avg_dumped_frames_ps(self, avg_dumped_frames_ps):
        """Sets the avg_dumped_frames_ps of this PerformanceMetricsByFeFcNodeRollup.

        Average dumped frames per second.  # noqa: E501

        :param avg_dumped_frames_ps: The avg_dumped_frames_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_dumped_frames_ps = avg_dumped_frames_ps

    @property
    def avg_loss_of_signal_count_ps(self):
        """Gets the avg_loss_of_signal_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average loss of signal count per second.  # noqa: E501

        :return: The avg_loss_of_signal_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_loss_of_signal_count_ps

    @avg_loss_of_signal_count_ps.setter
    def avg_loss_of_signal_count_ps(self, avg_loss_of_signal_count_ps):
        """Sets the avg_loss_of_signal_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        Average loss of signal count per second.  # noqa: E501

        :param avg_loss_of_signal_count_ps: The avg_loss_of_signal_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_loss_of_signal_count_ps = avg_loss_of_signal_count_ps

    @property
    def avg_invalid_crc_count_ps(self):
        """Gets the avg_invalid_crc_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average invalid crc count per second.  # noqa: E501

        :return: The avg_invalid_crc_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_invalid_crc_count_ps

    @avg_invalid_crc_count_ps.setter
    def avg_invalid_crc_count_ps(self, avg_invalid_crc_count_ps):
        """Sets the avg_invalid_crc_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        Average invalid crc count per second.  # noqa: E501

        :param avg_invalid_crc_count_ps: The avg_invalid_crc_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_invalid_crc_count_ps = avg_invalid_crc_count_ps

    @property
    def avg_loss_of_sync_count_ps(self):
        """Gets the avg_loss_of_sync_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average loss of sync count per second.  # noqa: E501

        :return: The avg_loss_of_sync_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_loss_of_sync_count_ps

    @avg_loss_of_sync_count_ps.setter
    def avg_loss_of_sync_count_ps(self, avg_loss_of_sync_count_ps):
        """Sets the avg_loss_of_sync_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        Average loss of sync count per second.  # noqa: E501

        :param avg_loss_of_sync_count_ps: The avg_loss_of_sync_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_loss_of_sync_count_ps = avg_loss_of_sync_count_ps

    @property
    def avg_invalid_tx_word_count_ps(self):
        """Gets the avg_invalid_tx_word_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average invalid transmission word count per second.  # noqa: E501

        :return: The avg_invalid_tx_word_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_invalid_tx_word_count_ps

    @avg_invalid_tx_word_count_ps.setter
    def avg_invalid_tx_word_count_ps(self, avg_invalid_tx_word_count_ps):
        """Sets the avg_invalid_tx_word_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        Average invalid transmission word count per second.  # noqa: E501

        :param avg_invalid_tx_word_count_ps: The avg_invalid_tx_word_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_invalid_tx_word_count_ps = avg_invalid_tx_word_count_ps

    @property
    def avg_prim_seq_prot_err_count_ps(self):
        """Gets the avg_prim_seq_prot_err_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average primitive sequence protocol error count per second.  # noqa: E501

        :return: The avg_prim_seq_prot_err_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_prim_seq_prot_err_count_ps

    @avg_prim_seq_prot_err_count_ps.setter
    def avg_prim_seq_prot_err_count_ps(self, avg_prim_seq_prot_err_count_ps):
        """Sets the avg_prim_seq_prot_err_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        Average primitive sequence protocol error count per second.  # noqa: E501

        :param avg_prim_seq_prot_err_count_ps: The avg_prim_seq_prot_err_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_prim_seq_prot_err_count_ps = avg_prim_seq_prot_err_count_ps

    @property
    def avg_link_failure_count_ps(self):
        """Gets the avg_link_failure_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Average link failure count per second.  # noqa: E501

        :return: The avg_link_failure_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._avg_link_failure_count_ps

    @avg_link_failure_count_ps.setter
    def avg_link_failure_count_ps(self, avg_link_failure_count_ps):
        """Sets the avg_link_failure_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        Average link failure count per second.  # noqa: E501

        :param avg_link_failure_count_ps: The avg_link_failure_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._avg_link_failure_count_ps = avg_link_failure_count_ps

    @property
    def max_dumped_frames_ps(self):
        """Gets the max_dumped_frames_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        The maximum dumped frames per second.  # noqa: E501

        :return: The max_dumped_frames_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_dumped_frames_ps

    @max_dumped_frames_ps.setter
    def max_dumped_frames_ps(self, max_dumped_frames_ps):
        """Sets the max_dumped_frames_ps of this PerformanceMetricsByFeFcNodeRollup.

        The maximum dumped frames per second.  # noqa: E501

        :param max_dumped_frames_ps: The max_dumped_frames_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_dumped_frames_ps = max_dumped_frames_ps

    @property
    def max_loss_of_signal_count_ps(self):
        """Gets the max_loss_of_signal_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        The maximum loss of signal count per second.  # noqa: E501

        :return: The max_loss_of_signal_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_loss_of_signal_count_ps

    @max_loss_of_signal_count_ps.setter
    def max_loss_of_signal_count_ps(self, max_loss_of_signal_count_ps):
        """Sets the max_loss_of_signal_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        The maximum loss of signal count per second.  # noqa: E501

        :param max_loss_of_signal_count_ps: The max_loss_of_signal_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_loss_of_signal_count_ps = max_loss_of_signal_count_ps

    @property
    def max_invalid_crc_count_ps(self):
        """Gets the max_invalid_crc_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        The maximum invalid crc count per second.  # noqa: E501

        :return: The max_invalid_crc_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_invalid_crc_count_ps

    @max_invalid_crc_count_ps.setter
    def max_invalid_crc_count_ps(self, max_invalid_crc_count_ps):
        """Sets the max_invalid_crc_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        The maximum invalid crc count per second.  # noqa: E501

        :param max_invalid_crc_count_ps: The max_invalid_crc_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_invalid_crc_count_ps = max_invalid_crc_count_ps

    @property
    def max_loss_of_sync_count_ps(self):
        """Gets the max_loss_of_sync_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        The maximum loss of sync count per second.  # noqa: E501

        :return: The max_loss_of_sync_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_loss_of_sync_count_ps

    @max_loss_of_sync_count_ps.setter
    def max_loss_of_sync_count_ps(self, max_loss_of_sync_count_ps):
        """Sets the max_loss_of_sync_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        The maximum loss of sync count per second.  # noqa: E501

        :param max_loss_of_sync_count_ps: The max_loss_of_sync_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_loss_of_sync_count_ps = max_loss_of_sync_count_ps

    @property
    def max_invalid_tx_word_count_ps(self):
        """Gets the max_invalid_tx_word_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        The maximum invalid transmission word count per second.  # noqa: E501

        :return: The max_invalid_tx_word_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_invalid_tx_word_count_ps

    @max_invalid_tx_word_count_ps.setter
    def max_invalid_tx_word_count_ps(self, max_invalid_tx_word_count_ps):
        """Sets the max_invalid_tx_word_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        The maximum invalid transmission word count per second.  # noqa: E501

        :param max_invalid_tx_word_count_ps: The max_invalid_tx_word_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_invalid_tx_word_count_ps = max_invalid_tx_word_count_ps

    @property
    def max_prim_seq_prot_err_count_ps(self):
        """Gets the max_prim_seq_prot_err_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        The maximum primitive sequence protocol error count per second.  # noqa: E501

        :return: The max_prim_seq_prot_err_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_prim_seq_prot_err_count_ps

    @max_prim_seq_prot_err_count_ps.setter
    def max_prim_seq_prot_err_count_ps(self, max_prim_seq_prot_err_count_ps):
        """Sets the max_prim_seq_prot_err_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        The maximum primitive sequence protocol error count per second.  # noqa: E501

        :param max_prim_seq_prot_err_count_ps: The max_prim_seq_prot_err_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_prim_seq_prot_err_count_ps = max_prim_seq_prot_err_count_ps

    @property
    def max_link_failure_count_ps(self):
        """Gets the max_link_failure_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        The maximum link failure count per second.  # noqa: E501

        :return: The max_link_failure_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: float
        """
        return self._max_link_failure_count_ps

    @max_link_failure_count_ps.setter
    def max_link_failure_count_ps(self, max_link_failure_count_ps):
        """Sets the max_link_failure_count_ps of this PerformanceMetricsByFeFcNodeRollup.

        The maximum link failure count per second.  # noqa: E501

        :param max_link_failure_count_ps: The max_link_failure_count_ps of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: float
        """

        self._max_link_failure_count_ps = max_link_failure_count_ps

    @property
    def repeat_count(self):
        """Gets the repeat_count of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501

        Number of times the metrics are repeated.  # noqa: E501

        :return: The repeat_count of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :rtype: int
        """
        return self._repeat_count

    @repeat_count.setter
    def repeat_count(self, repeat_count):
        """Sets the repeat_count of this PerformanceMetricsByFeFcNodeRollup.

        Number of times the metrics are repeated.  # noqa: E501

        :param repeat_count: The repeat_count of this PerformanceMetricsByFeFcNodeRollup.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                repeat_count is not None and repeat_count > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `repeat_count`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self._configuration.client_side_validation and
                repeat_count is not None and repeat_count < 0):  # noqa: E501
            raise ValueError("Invalid value for `repeat_count`, must be a value greater than or equal to `0`")  # noqa: E501

        self._repeat_count = repeat_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PerformanceMetricsByFeFcNodeRollup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PerformanceMetricsByFeFcNodeRollup):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PerformanceMetricsByFeFcNodeRollup):
            return True

        return self.to_dict() != other.to_dict()
