# coding: utf-8

"""
    PowerStore REST API

    Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )  # noqa: E501

    OpenAPI spec version: 3.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from prime.swagger_client.configuration import Configuration


class VolumeConfigureMetro(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'remote_system_id': 'str',
        'remote_appliance_id': 'str'
    }

    attribute_map = {
        'remote_system_id': 'remote_system_id',
        'remote_appliance_id': 'remote_appliance_id'
    }

    def __init__(self, remote_system_id=None, remote_appliance_id=None, _configuration=None):  # noqa: E501
        """VolumeConfigureMetro - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._remote_system_id = None
        self._remote_appliance_id = None
        self.discriminator = None

        self.remote_system_id = remote_system_id
        if remote_appliance_id is not None:
            self.remote_appliance_id = remote_appliance_id

    @property
    def remote_system_id(self):
        """Gets the remote_system_id of this VolumeConfigureMetro.  # noqa: E501

        The remote system with which the metro relationship will be established. The remote system must support metro volumes. name:{name} can be used instead of {id}. For example:'remote_system_id':'name:remote_system_name'  # noqa: E501

        :return: The remote_system_id of this VolumeConfigureMetro.  # noqa: E501
        :rtype: str
        """
        return self._remote_system_id

    @remote_system_id.setter
    def remote_system_id(self, remote_system_id):
        """Sets the remote_system_id of this VolumeConfigureMetro.

        The remote system with which the metro relationship will be established. The remote system must support metro volumes. name:{name} can be used instead of {id}. For example:'remote_system_id':'name:remote_system_name'  # noqa: E501

        :param remote_system_id: The remote_system_id of this VolumeConfigureMetro.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and remote_system_id is None:
            raise ValueError("Invalid value for `remote_system_id`, must not be `None`")  # noqa: E501

        self._remote_system_id = remote_system_id

    @property
    def remote_appliance_id(self):
        """Gets the remote_appliance_id of this VolumeConfigureMetro.  # noqa: E501

        A specific remote system appliance to which the volume will be assigned, if desired. By default, the system will choose an appropriate appliance based on space, load, and connectivity. name:{name} can be used instead of {id}. For example:'appliance_id':'name:appliance_name'  # noqa: E501

        :return: The remote_appliance_id of this VolumeConfigureMetro.  # noqa: E501
        :rtype: str
        """
        return self._remote_appliance_id

    @remote_appliance_id.setter
    def remote_appliance_id(self, remote_appliance_id):
        """Sets the remote_appliance_id of this VolumeConfigureMetro.

        A specific remote system appliance to which the volume will be assigned, if desired. By default, the system will choose an appropriate appliance based on space, load, and connectivity. name:{name} can be used instead of {id}. For example:'appliance_id':'name:appliance_name'  # noqa: E501

        :param remote_appliance_id: The remote_appliance_id of this VolumeConfigureMetro.  # noqa: E501
        :type: str
        """

        self._remote_appliance_id = remote_appliance_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VolumeConfigureMetro, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumeConfigureMetro):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VolumeConfigureMetro):
            return True

        return self.to_dict() != other.to_dict()
